### ISSUE TITLE
There is no Xamarin.Android.CometChat package found

### ISSUE THREAD

**Issue by lucky-c** [CometChat/xamarin-forms-chat-sdk-demo#1]
Hello, i want to try the CometChat demo using Visual Studio for Mac,
but it seems the "Xamarin.Android.CometChat" package is not exist, i also try to search on nuget.org.
How can i retrieve the package?

<img width="1764" alt="screen shot 2018-06-26 at 12 35 43" src="https://user-images.githubusercontent.com/12629759/41891258-ba3722aa-793d-11e8-8b0b-069d539609c5.png">

**Comment by adityagokula2210** [comment]
Hello, 
We regret the delay in response. Can you please check now as we have uploaded a new version of the packages for both android and ios. We have been able to successfully add the respective packages from the NuGet store. Please check now and let us know in case you still face any issues.

**Comment by lucky-c** [comment]
Hello Aditya,
Thank you for you response, i'm gladly to inform you the package now shown up in NuGet Store.
I'm successfully updating the package to version 7.2.1 by right-clicking the package, but not through restoring the package from solution (as seen from previous screenshot).

But now i'm facing new issue that the solution can't be build. I think it is related to the csproj file because the app.xaml and app.xaml.cs file are separated.
Please check the screenshot below.

<img width="1059" alt="ss" src="https://user-images.githubusercontent.com/12629759/42158952-47a5166e-7e1c-11e8-9f00-13df56dc5462.png">

**Comment by adityagokula2210** [comment]
This issue has been resolved.
