### ISSUE TITLE
Version 7.33 don't work

### ISSUE THREAD

**Issue by joseBarreto** [CometChat/xamarin-forms-chat-sdk-demo#10]
The Latest CometChat versions to Android do not work!
She does not install in new projects (Visual Studio 2017).
On ancient projets, (where the most current version can be installed) when we opened the main screen of the xamarin.cometchat.ui it kills our application!

![erroWiseView](https://user-images.githubusercontent.com/11754960/54436392-332b4280-4711-11e9-868c-2dec81b9a567.png)

![erroWiseView2](https://user-images.githubusercontent.com/11754960/54436400-36263300-4711-11e9-819f-1341f5d68f62.png)

**Comment by joseBarreto** [comment]
I'm using Android 8.1 in Samsung Galaxy S7

**Comment by sushantinscripts** [comment]
Hello,

Please install flurry nuget package from nuget store and try rebuilding.
![flurry](https://user-images.githubusercontent.com/30232716/54517181-f5375400-4986-11e9-80c7-a9af480d353e.PNG)

**Comment by joseBarreto** [comment]
> Hello,
> 
> Please install flurry nuget package from nuget store and try rebuilding.
> ![flurry](https://user-images.githubusercontent.com/30232716/54517181-f5375400-4986-11e9-80c7-a9af480d353e.PNG)

It worked!!!!

One question, in this version are push pushes disabled? I do not get push notification, only in this release;

**Comment by sushantinscripts** [comment]
We have released new CometChat Android Nuget version 7.33.1. We have fixed the notification issue in this. Kindly update and test once.

**Comment by joseBarreto** [comment]
fix!
