### ISSUE TITLE
Receive call while on another call, kill application [iOS]

### ISSUE THREAD

**Issue by joseBarreto** [CometChat/xamarin-forms-chat-sdk-demo#11]
In iOS when we are in a connection (by video or audio) if another user calls me the application close.

User_1 => connect to user_2;
User_3 => connect to user_1 while connected.

CometChat closes the application.

**Comment by vikrantwadate** [comment]
Hello,

We are testing our apps and trying to replicate the scenario mentioned by you. We will update you on the same once done.

Thanks.

**Comment by jigar-shethia01** [comment]
Hello,

We have encountered the issue you are facing. We will fix this in our upcoming release and we will update you once the issue is fixed.

Thanks.

**Comment by joseBarreto** [comment]
> Hello,
> 
> We have encountered the issue you are facing. We will fix this in our upcoming release and we will update you once the issue is fixed.
> 
> Thanks.


These versions 
Xamarin.iOS.CometChat  v7.35.0 and 
Xamarin.iOS.CometChat.UI  v7.35.0 are for this fix?

**Comment by vikrantwadate** [comment]
Hello,

We have fixed the issue you were facing and released v7.36.0. Please update to the latest SDK v7.36.0 to test the same and let us know you are feedback.

Thanks.

**Comment by joseBarreto** [comment]
Okay, we're testing, in version 7.37.0

**Comment by vikrantwadate** [comment]
Hello,

Please let us know if you are still facing the issue.

Thanks.

**Comment by joseBarreto** [comment]
> Hello,
> 
> Please let us know if you are still facing the issue.
> 
> Thanks.

Everything works fine now for iOS!
