### ISSUE TITLE
activities.CCGroupChatActivity.showCustomActionBarPopup

### ISSUE THREAD

**Issue by joseBarreto** [CometChat/xamarin-forms-chat-sdk-demo#12]
When deleting a group, through the CometChat panel, when I enter it in the mobile and click on the "..." of the group, the application closes with the following error.

### stack trace.
activities.CCGroupChatActivity.showCustomActionBarPopup CCGroupChatActivity.java:2130
activities.CCGroupChatActivity.onOptionsItemSelected CCGroupChatActivity.java:1346
android.app.Activity.onMenuItemSelected Activity.java:3527
android.support.v4.app.FragmentActivity.onMenuItemSelected FragmentActivity.java:380
android.support.v7.app.AppCompatActivity.onMenuItemSelected AppCompatActivity.java:195
android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected WindowCallbackWrapper.java:108
android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected WindowCallbackWrapper.java:108
android.support.v7.app.ToolbarActionBar$2.onMenuItemClick ToolbarActionBar.java:63
android.support.v7.widget.Toolbar$1.onMenuItemClick Toolbar.java:203
android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected ActionMenuView.java:780
android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected MenuBuilder.java:822
android.support.v7.view.menu.MenuItemImpl.invoke MenuItemImpl.java:171
android.support.v7.view.menu.MenuBuilder.performItemAction MenuBuilder.java:973
android.support.v7.view.menu.MenuBuilder.performItemAction MenuBuilder.java:963
android.support.v7.widget.ActionMenuView.invokeItem ActionMenuView.java:624
android.support.v7.view.menu.ActionMenuItemView.onClick ActionMenuItemView.java:150
android.view.View.performClick View.java:6897
android.widget.TextView.performClick TextView.java:12693
android.view.View$PerformClick.run View.java:26101
android.os.Handler.handleCallback Handler.java:789
android.os.Handler.dispatchMessage Handler.java:98
android.os.Looper.loop Looper.java:164
android.app.ActivityThread.main ActivityThread.java:6944
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.Zygote$MethodAndArgsCaller.run Zygote.java:327
com.android.internal.os.ZygoteInit.main ZygoteInit.java:1374

**Comment by mehtanishant** [comment]
Hello @joseBarreto,

We have identified and replicated the issue at our end. We are looking into it and fix the issue soon.
We appreciate your time and patience.

Thank You.

**Comment by joseBarreto** [comment]
Was this problem covered in v7.37.0?

**Comment by mehtanishant** [comment]
Hello @joseBarreto,

This has been resolved in the latest Xamarin release v7.37.0.

Thank You.
