### ISSUE TITLE
activities.CometChatActivity.setupTabs

### ISSUE THREAD

**Issue by joseBarreto** [CometChat/xamarin-forms-chat-sdk-demo#13]
When you try to create a group by mobile, the application closes.

### stack trace
activities.CometChatActivity.setupTabs CometChatActivity.java:775
activities.CometChatActivity.onCreate CometChatActivity.java:178
android.app.Activity.performCreate Activity.java:6272
android.app.Instrumentation.callActivityOnCreate Instrumentation.java:1108
android.app.ActivityThread.performLaunchActivity ActivityThread.java:2387
android.app.ActivityThread.handleLaunchActivity ActivityThread.java:2494
android.app.ActivityThread.access$900 ActivityThread.java:157
android.app.ActivityThread$H.handleMessage ActivityThread.java:1356
android.os.Handler.dispatchMessage Handler.java:102
android.os.Looper.loop Looper.java:148
android.app.ActivityThread.main ActivityThread.java:5530
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run ZygoteInit.java:734
com.android.internal.os.ZygoteInit.main ZygoteInit.java:624

**Comment by joseBarreto** [comment]
any news about this problem?

**Comment by mehtanishant** [comment]
Hello @joseBarreto,

We are trying to replicate the mentioned crash at our end, however, the groups are getting created from the mobile app. Kindly let us know if this is happening in any specific scenario at your end.

Thank You.

**Comment by joseBarreto** [comment]
Was this problem covered in v7.37.0?

**Comment by mehtanishant** [comment]
Hello @joseBarreto,

We would like to inform that we were unable to replicate this issue at our end. We also tried to replicate this in the latest release v7.37.0. We suggest using the latest Xamarin package and check once at your end.

Thank You.

**Comment by joseBarreto** [comment]
as at this moment we can not change the version of xamarin, we will only disable the creation of groups via mobile
