### ISSUE TITLE
helpers.CCSubcribe$4.onGroupActionMessageReceived

### ISSUE THREAD

**Issue by joseBarreto** [CometChat/xamarin-forms-chat-sdk-demo#14]
**I DO NOT KNOW WHAT YOU DID, MORE WHEN WE OPENED COMETCHAT AND LET'S GO TO CONTACT LIST YOU CLOSE OUR APPLICATION.!**
THIS IS IN PRODUCTION, AND OUR USERS ARE WITH APPLICATION CLOSING !!!!!
THAT WAS NOT SO SO MORNING OF THE DAY 03/04/2019. BUT NOW IT'S JUST OPENING THE CHAT AND MY  APPLICATION IS CLOSED.

CODE OF ERRORS IN AppCenter.

BUG TRACE

helpers.CCSubcribe$4.onGroupActionMessageReceived CCSubcribe.java:557
com.inscripts.helpers.MessageHelper.handleOneOnOneMessage MessageHelper.java:504
com.inscripts.transports.CometserviceOneOnOne.handleMessage CometserviceOneOnOne.java:330
com.inscripts.transports.CometserviceOneOnOne.processFirebaseMessage CometserviceOneOnOne.java:499
com.inscripts.transports.CometserviceOneOnOne.access$200 CometserviceOneOnOne.java:53
com.inscripts.transports.CometserviceOneOnOne$2.onDataChange CometserviceOneOnOne.java:139
com.google.android.gms.internal.zzduz.zza
com.google.android.gms.internal.zzdwu.zzbvb
com.google.android.gms.internal.zzdxa.run
android.os.Handler.handleCallback Handler.java:789
android.os.Handler.dispatchMessage Handler.java:98
android.os.Looper.loop Looper.java:164
android.app.ActivityThread.main ActivityThread.java:6944
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.Zygote$MethodAndArgsCaller.run Zygote.java:327
com.android.internal.os.ZygoteInit.main ZygoteInit.java:1374

**Comment by joseBarreto** [comment]
We try to contact your "Support", but I also get error there.


![image_2019_04_04T02_22_04_055Z](https://user-images.githubusercontent.com/11754960/55525462-79682780-5667-11e9-8e43-7251d19e394c.png)

**Comment by leandrobcb** [comment]
I am getting this error message when sending message and then the application closes

java.util.Timer.scheduleAtFixedRate Timer.java:523
com.inscripts.heartbeats.CCHeartbeat.startHeartbeat CCHeartbeat.java:186
com.inscripts.heartbeats.CCHeartbeat.changeHybridHeartbeatInverval CCHeartbeat.java:206
cometchat.inscripts.com.cometchatcore.coresdk.CometChat.resetOneOnOneHeartbeatInterval CometChat.java:1075
cometchat.inscripts.com.cometchatcore.coresdk.CometChat.sendMessage CometChat.java:3046
activities.CCSingleChatActivity.sendTextMessage CCSingleChatActivity.java:2299
activities.CCSingleChatActivity.sendTextMessage CCSingleChatActivity.java:2293
activities.CCSingleChatActivity.onClick CCSingleChatActivity.java:1215
android.view.View.performClick View.java:5210
android.view.View$PerformClick.run View.java:21294
android.os.Handler.handleCallback Handler.java:739
android.os.Handler.dispatchMessage Handler.java:95
android.os.Looper.loop Looper.java:148
android.app.ActivityThread.main ActivityThread.java:5530
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run ZygoteInit.java:734
com.android.internal.os.ZygoteInit.main ZygoteInit.java:624

![image](https://user-images.githubusercontent.com/29041936/55527409-45910000-566f-11e9-85b8-5632a8071a27.png)

**Comment by mehtanishant** [comment]
Hello @joseBarreto,

We are looking into the crash issue mentioned by you and trying to replicate the same at our environment. We will keep you posted about the same. We appreciate your time and patience.

Thank You.

**Comment by leandrobcb** [comment]
any news on this subject?

**Comment by joseBarreto** [comment]
Was this problem covered in v7.37.0?
