### ISSUE TITLE
com.inscripts.heartbeats.CCHeartbeat.startHeartbeat

### ISSUE THREAD

**Issue by joseBarreto** [CometChat/xamarin-forms-chat-sdk-demo#15]
Some clients, when they are going to send message receive this error, and the application closes.

![image](https://user-images.githubusercontent.com/11754960/55559872-7ac83d00-56c5-11e9-9ae6-8762606a3837.png)

**Comment by leandrobcb** [comment]
Our customers are complaining about the instability of the chat, do you have a forecast?

**Comment by leandrobcb** [comment]
any news on this subject?

**Comment by mehtanishant** [comment]
Hello @leandrobcb,

We would like to inform that you need to invoke initCometChatServices() method, inside the success callback of login() method. This will resolve the crash issue you are facing.

Thank You

**Comment by joseBarreto** [comment]
> Hello @leandrobcb,
> 
> We would like to inform that you need to invoke initCometChatServices() method, inside the success callback of login() method. This will resolve the crash issue you are facing.
> 
> Thank You

is this method available in which namespace?

**Comment by joseBarreto** [comment]
Do you have any examples of how to use this method?

**Comment by joseBarreto** [comment]
I put the code, after login, calling the code of the namespace "Cometchat.Inscripts.Com.Cometchatcore.Coresdk.CometChat"
I still have the same mistakes.

**Comment by joseBarreto** [comment]
> Hello @leandrobcb,
> We would like to inform that you need to invoke initCometChatServices() method, inside the success callback of login() method. This will resolve the crash issue you are facing.
> Thank You

any other tips?

**Comment by mehtanishant** [comment]
Hello @joseBarreto,

You can refer the following code snippet to invoke the initCometChatServices method.

 cc.InitCometChatServices(activity, new CometChatCallback(success => successCall(success), fail => failCall(fail)));

where cc is the CometChat instance.

Kindly check and let us know if this solves your issue.

Thank You
