### ISSUE TITLE
tab  "Contacts" ignores friends list

### ISSUE THREAD

**Issue by joseBarreto** [CometChat/xamarin-forms-chat-sdk-demo#16]
Good Morning,
we're having a problem with the display of the contacts.

Steps:
We assemble the list of users' friends, grouper by a specific rule.
The problem that now all users can find, searching for chat in the app, or in some cases (we do not know what the relationship of these cases) just opening the "contacts" tab already display all users of the system.

**Comment by joseBarreto** [comment]
We found this in the new and old versions for iOS and Android

**Comment by lgurgel** [comment]
Please, we need a feedback urgently.

**Comment by vikrantwadate** [comment]
Hello,

We are testing the scenario mentioned by you we will shortly provide you with an update.

Thanks.

**Comment by lgurgel** [comment]
Its urgent! We will loose an important customer if we do not solve this. The list of users cannot be mixed between different groups and accounts.



Laerte Gurgel
CEO Iberia-Brasil
laerte.gurgel@fieldcorp.com.br	
O Brazil: +55 11 4240 2138
M Brazil: +55 11 9 9524 7297
M Spain: +34 727 741 773
www.fieldcorp.com.br

**Comment by vikrantwadate** [comment]
Hello,

We have made some changes in the CometChat Administration panel. Now, you will be able to see the friends of the logged in user only. Please check and let us know if this fulfills your requirement. You can also make the changes in the CometChat Administration panel. To make the changes please follow the steps below :

1)  Log in to "https://secure.cometchat.com".
2) Click on the **Manage** button and you will be able to see the administration panel.
3) Click on the **Settings** on the left-hand side under the **CUSTOMIZE & INSTALL** section.
4) Click on **General** and **One-on-one Chat** setting will be open for you. 

Here, you can make the changes under the **In Contacts tab, show:** label to show the specific Contact list as per your requirement.

If you are still facing any issue please let us know in detail.

Thanks.

**Comment by lgurgel** [comment]
Thanks,

We will test it now.



Laerte Gurgel
CEO Iberia-Brasil
laerte.gurgel@fieldcorp.com.br	
O Brazil: +55 11 4240 2138
M Brazil: +55 11 9 9524 7297
M Spain: +34 727 741 773
www.fieldcorp.com.br

**Comment by joseBarreto** [comment]
Setting for "all friends. Online-Offline" seems to have worked well.
Thank you!
