### ISSUE TITLE
Xamarin Forms, not able to find License Key in Admin Panel

### ISSUE THREAD

**Issue by SagarPanwala** [CometChat/xamarin-forms-chat-sdk-demo#26]
Hi,
I'm  currently want to try free trial version and doing my setup with Xamarin Forms.
I downloaded sample application, but I'm not able to find License Key neither from Setting nor Api key Section.

Also in Api key there are two Api keys, authOnly and FullAccess which one I have to use.

here is the guide I'm following
https://developer.cometchat.com/docs/xamarin-forms-quick-start

which has below paragraph to get keys
update the License Key and API Key in the MainPage.xaml.cs file in the project. (you can get these values from CometChat Admin Panel -> Settings -> API Keys

**Comment by bhoiraashay** [comment]
Hello @SagarPanwala,

I see that you have a CometChat Pro subscription. The documentation you are referring to, i.e https://developer.cometchat.com/docs/xamarin-forms-quick-start is incorrect, it is for our Go solution. 

For Pro, the correct documentation you have to look at is:

http://prodocs.cometchat.com/

Having said that, I would also like to inform you that CometChat Pro does not have support for Xamarin yet. You can sign up to feedback.cometchat.com and upvote here:

http://feedback.cometchat.com/cometchat-pro/p/client-sdk-for-xamarin

You will be posted with updates on the progress.

**Comment by SagarPanwala** [comment]
Thanks for the clarification,

I believe doc is easy but to find proper doc is too much complicate.

In the first page of website, they have mentioned Xamarin is supported and
example is also given, now I don't understand why you say chat is not
supported.

**Comment by anantgarg** [comment]
Hi Sagar,

Sorry for the confusion. Currently CometChat Pro does not support Xamarin.

We have support for Xamarin in CometChat Go. You can signup at https://www.cometchat.com/go/pricing

**Comment by SagarPanwala** [comment]
So can you please explain me what is difference between Go and Pro?
I read on site, it says for developer need to use pro and for manager use
Go.

But here you are saying, Xamarin support for Go.

**Comment by anantgarg** [comment]
Yes, you are correct. We will be building an integration for Xamarin for CometChat Pro in the near future. In the meanwhile, you can use CometChat Go.

**Comment by sgiulians** [comment]
Hi there,
did you manage to build an integration with Xamarin for the PRO version?

**Comment by devperson** [comment]
@anantgarg @bhoiraashay  Any update with Xamarin for PRO?
