### ISSUE TITLE
Group chats crash on Android

### ISSUE THREAD

**Issue by harry-gordon** [CometChat/xamarin-forms-chat-sdk-demo#4]
Whenever I start a group chat in the sample any Android client trying to view the group chat crashes with the following exception:

```Java.Lang.NullPointerException: Attempt to write to field 'int android.support.v7.widget.RecyclerView$ViewHolder.mItemViewType' on a null object reference```

Here is the full output: [output.txt](https://github.com/CometChat/xamarin-forms-chat-sdk-demo/files/2566299/output.txt).

**Comment by jitvarpatil** [comment]
Hello,

Thanks for contacting us. We are looking into this will provide you with a solution shortly.

**Comment by harry-gordon** [comment]
Thanks @jitvarpatil, if you need any more information from me just let me know.

**Comment by jitvarpatil** [comment]
Hi @harry-gordon, We have fixed this issue in latest version v7.19.1. 

Feel free to contact us for any other queries.
