### ISSUE TITLE
OnWindowClose event does not exist / implemented for iOS.

### ISSUE THREAD

**Issue by joseBarreto** [CometChat/xamarin-forms-chat-sdk-demo#6]
For android implementation
["cometchat.LaunchCometChat"] accepts as parameter the onWindowClose, which is calling when pressing the android back button.

For the implementation of iOS ["cometchat.LaunchCometChat"] **there is no option to pass this event**, and when we click on the "X" at the top of the page, that does the action of coming back on iOS we do not have a return method that cometChar was closed.

Is this an error with the binding or is there any way to capture the closed cometChat for iOS?

**Comment by joseBarreto** [comment]
this "X"

![image](https://user-images.githubusercontent.com/11754960/53663285-22c09580-3c44-11e9-84a6-afb8ba4c3df8.png)

**Comment by jigar-shethia01** [comment]
Hello,

When you click the "X" button you will get an OnLauchSuccess of LaunchCometChat method. You will get login = "Window Closed" event. 

Thanks.

**Comment by joseBarreto** [comment]
[BindingImpl(BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
        [Export("launchCometChat:observer:userInfo:groupInfo:onMessageReceive:success:failure:onLogout:")]
        public virtual void LaunchCometChat(bool isFullScreen, UIViewController currentView, [BlockProxy(typeof(NIDActionArity1V0))] Action<NSDictionary> userInfo, [BlockProxy(typeof(NIDActionArity1V0))] Action<NSDictionary> groupInfo, [BlockProxy(typeof(NIDActionArity1V0))] Action<NSDictionary> onMessageReceive, [BlockProxy(typeof(NIDActionArity1V0))] Action<NSDictionary> **success**, [BlockProxy(typeof(NIDActionArity1V1))] Action<NSError> failure, [BlockProxy(typeof(NIDActionArity1V0))] Action<NSDictionary> onLogout);



This success? 
Is not it called for the return of success when CometChat is opened?

**Comment by joseBarreto** [comment]
Is there any reason these calls are different between iOS and Android?

> Hello,
> 
> When you click the "X" button you will get an OnLauchSuccess of LaunchCometChat method. You will get login = "Window Closed" event.
> 
> Thanks.

**Comment by jigar-shethia01** [comment]
Hello,

The implementation is different for both the platforms as per the project structure. However, you can use the login = "Window Closed" event which you get when you click the "X" button.

Thanks.
