### ISSUE TITLE
Failed to publish iOS application using CometChat [MessageSDKFramework]

### ISSUE THREAD

**Issue by joseBarreto** [CometChat/xamarin-forms-chat-sdk-demo#8]
Hello,
We are submitting our applications to the Apple Store, however we are having issues with MessageSDKFramework. This framework is external to our project and in all the researches we found it is related to the CometChat.

Our error is at the moment we upload the application through XCode.

ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload / ... iOS.app/MessageSDKFramework.bundle' does not contain an executable bundle. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using the CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue. "

Can you help us with this mistake?
In our plist there is nothing referencing this framework, not even something from google as other users have reported.

**Comment by vikrantwadate** [comment]
Hello,

We will release the new Xamarin SDK which will resolve this issue. We will update you once have done.

Thanks.

**Comment by vikrantwadate** [comment]
Hello,

We suggest you update to our latest SDK v7.33.1, it should resolve your issue and you can proceed with publishing the app to App Store.

Thanks.

**Comment by joseBarreto** [comment]
Okay, we're downloading and starting the test cycle.

> Olá,
> 
> Sugerimos que você atualize para o nosso mais recente SDK v7.33.1, ele deve resolver seu problema e você pode prosseguir com a publicação do aplicativo na App Store.
> 
> Obrigado.

**Comment by joseBarreto** [comment]
> Hello,
> 
> We suggest you update to our latest SDK v7.33.1, it should resolve your issue and you can proceed with publishing the app to App Store.
> 
> Thanks.

We still get the same error.

Versions Nuget
![1](https://user-images.githubusercontent.com/11754960/54283418-b9fae680-457c-11e9-97b9-4255d2277eab.png)



XCode - > Application Loader.
![Captura de Tela 2019-03-13 às 10 24 20](https://user-images.githubusercontent.com/11754960/54283433-c67f3f00-457c-11e9-9025-c75a978a3e59.png)


.ipa->MessageSDKFramework->pList
![image](https://user-images.githubusercontent.com/11754960/54282994-ed894100-457b-11e9-85b0-39178d118170.png)

**Comment by vikrantwadate** [comment]
Hello,

We will suggest you remove the Executable file from the info.plist file and upload the app to App Store.

And please let us know on which platform are you trying to upload the application is it on native iOS or Xamarin.

Thanks.

**Comment by joseBarreto** [comment]
Xamarin.iOS, using visual studio for Windows / Mac
We have made this change, however an altered .ipa file can not be sent to the store in Distribution version.
We open the ipa only to confirm that the error was with the sdk of CometChat, however if we close it the signature is lost.

As in the image below.

![image](https://user-images.githubusercontent.com/11754960/54285325-80c47580-4580-11e9-98ca-9a1229bed13b.png)

**Comment by vikrantwadate** [comment]
Hello,
 
We saw the screenshot however this is some sort of issue which should be solved at your end. The problem related to MessageSDKFramework.bundle is solved now as the error in the screenshot refers to some different error otherwise it would have been the same as earlier. There could be the issue with your code signing, we suggest you to properly archive the .ipa file and try uploading to the store. 

Thanks.

**Comment by joseBarreto** [comment]
> Hello,
> 
> We saw the screenshot however this is some sort of issue which should be solved at your end. The problem related to MessageSDKFramework.bundle is solved now as the error in the screenshot refers to some different error otherwise it would have been the same as earlier. There could be the issue with your code signing, we suggest you to properly archive the .ipa file and try uploading to the store.
> 
> Thanks.

@vikrantwadate 
This error I just made if I take the step you asked me to manually remove the tag from the plist.
If I do not I fall into the first error of this post.

**Comment by joseBarreto** [comment]
> Hello,
> 
> We will suggest you remove the Executable file from the info.plist file and upload the app to App Store.
> 
> And please let us know on which platform are you trying to upload the application is it on native iOS or Xamarin.
> 
> Thanks.

Here you asked me to remove the tag. When changing a .ipa it loses the certificate settings, so we can not change them.
And so we ask you to correct the version of cometchat, because any app we created with it can not be sent due to the error of the MessageSDKFramework.

**Comment by joseBarreto** [comment]
What we've tried:
1st  Generate the ipa and submit it to the store: Error by the MessageSDKFramework tag.

2st Generate the ipa, open it as zip, change the .plist of the MessageSDKFramework, close it as zip and put it to .ipa: Certificate error because the ipa has changed.

What you have asked to do, which is to change the .ipa, can not be done.

https://docs.microsoft.com/en-us/xamarin/ios/troubleshooting/questions/modify-ipa

**Comment by vikrantwadate** [comment]
Hello,

Do not edit the .ipa file just update to the latest version and create new .ipa with it and try to upload to the store. The issue should not come as we have removed the Executable file form the latest version 7.33.1 itself.

Thanks.

**Comment by joseBarreto** [comment]
We generate by visual studio in Windows, and we go up by the mac. With version 7.33.1 it worked!

for some reason we could not get through visual studio for mac.

Thank you!

![image](https://user-images.githubusercontent.com/11754960/54300643-099cda80-459c-11e9-9102-e80ad7d40f89.png)
