### ISSUE TITLE
permissions for Android.

### ISSUE THREAD

**Issue by leandrobcb** [CometChat/xamarin-forms-chat-sdk-demo#9]
Hello,
I have a question regarding the CometChat permissions for Android.

Do you use this permission or add it to the "send_sms" manisfesto or any other of the call logs group?

After I added cometChat to my project, when submitting it to Google Store indicates that a new permission has been added to "send_sms", but it does not exist in my manifest.

Before we put the Cometchat we did not have this message.

![image](https://user-images.githubusercontent.com/29041936/54307110-9ac67e00-45a9-11e9-9997-9e52e4d6b6fc.png)

![image](https://user-images.githubusercontent.com/29041936/54307130-a9ad3080-45a9-11e9-8937-e78b234e43b5.png)

**Comment by joseBarreto** [comment]
After hours breaking head with publishing in the Apple Store, I tried publishing the version of Android to Google Play and I'm having the same problem.

**Comment by leandrobcb** [comment]
> After hours breaking head with publishing in the Apple Store, I tried publishing the version of Android to Google Play and I'm having the same problem.


To confirm that the problem was in CometChat I removed all the implementation and Nugets from CometChat.Android, I generated a new apk and sent it to the store. It passed smoothly. But with the version that has CometChat I failed with the "read_sms" permission on Google Play.

I really believe that the CometChat team does not have applications published in Google and Apple , because these errors are basic, and would be with any user who tries to send the application to the stores.

![image](https://user-images.githubusercontent.com/29041936/54310218-a0739200-45b0-11e9-809f-ae91c88c257f.png)

**Comment by joseBarreto** [comment]
any idea what it might be?

**Comment by leandrobcb** [comment]
I'm with the customer charging for a product update

**Comment by leandrobcb** [comment]
> Hello,
> I have a question regarding the CometChat permissions for Android.
> 
> Do you use this permission or add it to the "send_sms" manisfesto or any other of the call logs group?
> 
> After I added cometChat to my project, when submitting it to Google Store indicates that a new permission has been added to "send_sms", but it does not exist in my manifest.
> 
> Before we put the Cometchat we did not have this message.
> 
> ![image](https://user-images.githubusercontent.com/29041936/54307110-9ac67e00-45a9-11e9-9997-9e52e4d6b6fc.png)
> 
> ![image](https://user-images.githubusercontent.com/29041936/54307130-a9ad3080-45a9-11e9-8937-e78b234e43b5.png)

I'm with the client charging a new version of the system

**Comment by mehtanishant** [comment]
Hello @leandrobcb,

We had the 'send_sms' permission included in our package earlier, however, in the recent Nuget release we have addressed this issue and removed the permission entirely for Android. We suggest updating to the latest NuGet package available.

Kindly try this and let us know your feedback.

**Comment by joseBarreto** [comment]
> Hello @leandrobcb,
> 
> We had the 'send_sms' permission included in our package earlier, however, in the recent Nuget release we have addressed this issue and removed the permission entirely for Android. We suggest updating to the latest NuGet package available.
> 
> Kindly try this and let us know your feedback.

Unable to update package.
For new projects I have this error:
https://github.com/CometChat/xamarin-forms-chat-sdk-demo/issues/7

For projects that can update when we open the interface it closes the application in the latest version of CometChat 7.32.1

**Comment by leandrobcb** [comment]
> > Hello @leandrobcb,
> > We had the 'send_sms' permission included in our package earlier, however, in the recent Nuget release we have addressed this issue and removed the permission entirely for Android. We suggest updating to the latest NuGet package available.
> > Kindly try this and let us know your feedback.
> 
> Unable to update package.
> For new projects I have this error:
> #7
> 
> For projects that can update when we open the interface it closes the application in the latest version of CometChat 7.32.1

I also have the same problem with the latest version of my project.
The Xamarin.Android.CometChat.UI v7.32.1 package closes the application as it opens. So I'm using v7.22.0.

Xamarin.Android.CometChat v7.32.1 works normally.

**Comment by sushantinscripts** [comment]
@leandrobcb @joseBarreto 

We have released xamarin nuget 7.33.0 with more monoandroid related changes. Kindly check if this resolves the issue at your end.

**Comment by joseBarreto** [comment]
> @leandrobcb @joseBarreto
> 
> We have released xamarin nuget 7.33.0 with more monoandroid related changes. Kindly check if this resolves the issue at your end.

**Unfortunately it does not work, yet.**

https://github.com/CometChat/xamarin-forms-chat-sdk-demo/issues/10

**Comment by joseBarreto** [comment]
> > > Hello @leandrobcb,
> > > We had the 'send_sms' permission included in our package earlier, however, in the recent Nuget release we have addressed this issue and removed the permission entirely for Android. We suggest updating to the latest NuGet package available.
> > > Kindly try this and let us know your feedback.
> > 
> > 
> > Unable to update package.
> > For new projects I have this error:
> > #7
> > For projects that can update when we open the interface it closes the application in the latest version of CometChat 7.32.1
> 
> I also have the same problem with the latest version of my project.
> The Xamarin.Android.CometChat.UI v7.32.1 package closes the application as it opens. So I'm using v7.22.0.
> 
> Xamarin.Android.CometChat v7.32.1 works normally.

install flurry nuget package from nuget store and try rebuilding.

https://github.com/CometChat/xamarin-forms-chat-sdk-demo/issues/10
